version: '2'

services:
  web:
    build: .
    volumes:
      - ./:/code
    ports:
      - "5100:5000"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: "mongo:4.4.4-bionic"
    restart: always
    volumes:
      - ../mongo_data:/data
