version: '2'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./:/code

  mongo:
    image: "mongo:4.4.4-bionic"
    restart: always
    volumes:
      - ../mongo_data:/data