version: '3'

services:
  web:
    build:
      context: ".."
      dockerfile: docker/web.dockerfile
    restart: always
    volumes:
      - ../:/code
    depends_on:
      - postgres
      - redis
    env_file:
      - ../.env
    environment:
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - LOGLEVEL=DEBUG
      - "AWI_TEST_MODE=${AWI_TEST_MODE}"

  runner:
    build:
      context: ".."
      dockerfile: docker/runner.dockerfile
    volumes:
      - ../:/code:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_data:/runner_data
    environment:
      - LOGLEVEL=DEBUG

  nginx:
    build:
      context: ".."
      dockerfile: docker/nginx.dockerfile
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - web
      - runner
      - prometheus
    volumes:
      - ../app/static:/static:ro

  postgres:
    image: "postgres:14"
    restart: always
    volumes:
      - "${POSTGRES_VOLUME_BIND:-postgres_data:/var/lib/postgresql/data}"
    env_file:
      - ../.env

  redis:
    image: "redis:6"
    restart: always
    volumes:
      - redis_data:/data

  prometheus:
    build:
      context: ".."
      dockerfile: docker/prometheus.dockerfile
    volumes:
      - prometheus_data:/prometheus

volumes:
  postgres_data:
  runner_data:
  redis_data:
  prometheus_data:
