version: '3'

services:
  web:
    build:
      context: ".."
      dockerfile: docker/web.dockerfile
    volumes:
      - ../:/code:ro
    depends_on:
      - mongo
    env_file:
      - ../.env
  
  runner:
    build:
      context: ".."
      dockerfile: docker/runner.dockerfile
    volumes:
      - ../:/code:ro
  
  nginx:
    build:
      context: ".."
      dockerfile: docker/nginx.dockerfile
    ports:
      - 8080:80
    depends_on:
      - web
      - runner
    volumes:
      - ../app/static:/static:ro

  mongo:
    image: "mongo:4.4.4-bionic"
    restart: always
    volumes:
      - ../.mongo_data:/data
