version: '3'

services:
  web:
    build:
      context: ".."
      dockerfile: docker/web.dockerfile
    restart: always
    volumes:
      - ../:/code
    depends_on:
      - postgres
    env_file:
      - ../.env
    environment:
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1

  runner:
    build:
      context: ".."
      dockerfile: docker/runner.dockerfile
    volumes:
      - ../:/code:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_data:/runner_data
    environment:
      - LOGLEVEL=DEBUG

  nginx:
    build:
      context: ".."
      dockerfile: docker/nginx.dockerfile
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - web
      - runner
    volumes:
      - ../app/static:/static:ro

  postgres:
    image: "postgres:14"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  postgres_data:
  runner_data:
