version: '3'

services:
  web:
    build:
      context: ".."
      dockerfile: docker/web.dockerfile
    restart: always
    depends_on:
      - mongo
    env_file:
      - ../.env
    command: poetry run waitress-serve --port 80 app:app

  runner:
    build:
      context: ".."
      dockerfile: docker/runner.dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_data:/runner_data
    restart: always

  nginx:
    build:
      context: ".."
      dockerfile: docker/nginx.dockerfile
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - web
      - runner
    restart: always

  mongo:
    image: "mongo:4.4.4-bionic"
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  runner_data:
