"""empty message

Revision ID: 42023eebcfd8
Revises: fa5bd4e16b7c
Create Date: 2022-04-26 13:33:40.043386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42023eebcfd8'
down_revision = 'fa5bd4e16b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_consumer', sa.Column('in_use', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_consumer', 'in_use')
    # ### end Alembic commands ###
