"""empty message

Revision ID: 498730870534
Revises: 42023eebcfd8
Create Date: 2022-04-26 14:40:21.894883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498730870534'
down_revision = '42023eebcfd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('tool_consumer_id', sa.Integer(), nullable=True))
    op.add_column('problem', sa.Column('resource_link_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'problem', ['tool_consumer_id', 'resource_link_id'])
    op.create_foreign_key(None, 'problem', 'tool_consumer', ['tool_consumer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.drop_constraint(None, 'problem', type_='unique')
    op.drop_column('problem', 'resource_link_id')
    op.drop_column('problem', 'tool_consumer_id')
    # ### end Alembic commands ###
