"""empty message

Revision ID: 7340300b3dca
Revises: 2eb329127447
Create Date: 2022-04-26 17:53:24.090556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7340300b3dca'
down_revision = '2eb329127447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('checker_config', sa.String(), nullable=True))
    op.drop_column('problem', 'checker_config_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('checker_config_json', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('problem', 'checker_config')
    # ### end Alembic commands ###
