"""empty message

Revision ID: 969e0e899721
Revises: 7340300b3dca
Create Date: 2022-04-28 12:27:36.030449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969e0e899721'
down_revision = '7340300b3dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('is_instructor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'is_instructor')
    # ### end Alembic commands ###
