"""empty message

Revision ID: c44970e54051
Revises: 65ae206d9c30
Create Date: 2022-04-11 13:17:28.002971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44970e54051'
down_revision = '65ae206d9c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debug_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('source_code', sa.String(), nullable=False),
    sa.Column('arch', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('is_interactive', sa.Boolean(), nullable=False),
    sa.Column('cpu_time_used', sa.Float(), nullable=True),
    sa.Column('real_time_used', sa.Float(), nullable=True),
    sa.Column('memory_used', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debug_session')
    # ### end Alembic commands ###
