"""empty message

Revision ID: fa5bd4e16b7c
Revises: c44970e54051
Create Date: 2022-04-26 13:23:13.605456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5bd4e16b7c'
down_revision = 'c44970e54051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_consumer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumer_key', sa.String(), nullable=False),
    sa.Column('consumer_secret', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=True),
    sa.Column('instance_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consumer_key')
    )
    op.alter_column('debug_session', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('debug_session', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('submission', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('user', sa.Column('tool_consumer_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_lti_tool_consumer_guid_lti_user_id_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['tool_consumer_id', 'lti_user_id'])
    op.create_foreign_key(None, 'user', 'tool_consumer', ['tool_consumer_id'], ['id'])
    op.drop_column('user', 'lti_tool_consumer_guid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lti_tool_consumer_guid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_lti_tool_consumer_guid_lti_user_id_key', 'user', ['lti_tool_consumer_guid', 'lti_user_id'])
    op.drop_column('user', 'tool_consumer_id')
    op.alter_column('submission', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('debug_session', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('debug_session', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('tool_consumer')
    # ### end Alembic commands ###
