name: Deploy Test on PR

on: pull_request


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Deploy
        run: ./manage.py run --port 80 --prod --detach
      - name: Change hosts
        run: sudo echo "127.0.0.1 asm.moevm.info" | sudo tee -a /etc/hosts
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s
      - name: Run health check
        run: curl -f asm.moevm.info/_health
