name: Selenium Test on PR

on: pull_request

    
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install requirements
        run: |
          python3.10 -m pip install poetry selenium
          poetry install --no-interaction --no-ansi
      - name: Create .env
        run: echo "AWI_SECRET_KEY=secret_key" > .env
      - name: Build docker
        run: docker-compose -f docker/develop.docker-compose.yml -p asm_web_debug build --build-arg RUNMODE=test
      - name: Run docker
        run: docker-compose -f docker/develop.docker-compose.yml -p asm_web_debug up -d
      - name: Check service port 
        run: nc -vz localhost 5100
      - name: Run tests
        run: |
          cd tests/selenium
          PATH=/$PATH xvfb-run python3.10 main.py http://127.0.0.1:5100
      - name: Check logs 
        run: docker-compose -f docker/develop.docker-compose.yml logs
        if: always()
