name: Selenium Test on PR

on: pull_request


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python3 -m pip install poetry
          poetry install --no-interaction --no-ansi
      - name: Run web server
        run: ./manage.py run -d --port 5100
      - name: Create test user
        run: ./manage.py create-admin --username test_username --password test_password
      - name: Run tests
        run: |
          cd tests/selenium
          xvfb-run poetry run ./scripts/run_tests.sh
